/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary': '#ffffff',
        'error-container': '#ffdad6',
        'on-secondary-container': '#636262',
        'error': '#ba1a1a',
        'on-tertiary-fixed-variant': '#004880',
        'on-secondary-fixed': '#1c1b1b',
        'surface-tint': '#aa3600',
        'on-tertiary-container': '#fdfcff',
        'outline-variant': '#e5beb2',
        'inverse-primary': '#ffb59c',
        'secondary-fixed-dim': '#c8c6c5',
        'on-secondary-fixed-variant': '#474746',
        'on-background': '#281812',
        'on-error': '#ffffff',
        'surface-bright': '#fff8f6',
        'tertiary-fixed-dim': '#a1c9ff',
        'on-primary': '#ffffff',
        'outline': '#907065',
        'on-primary-fixed': '#390c00',
        'on-tertiary-fixed': '#001c37',
        'surface-container': '#ffe9e3',
        'primary-fixed-dim': '#ffb59c',
        'tertiary-fixed': '#d2e4ff',
        'surface-container-highest': '#fbdcd3',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#ffe2d9',
        'surface-variant': '#fbdcd3',
        'primary-fixed': '#ffdbcf',
        'inverse-on-surface': '#ffede8',
        'surface-dim': '#f2d4ca',
        'tertiary': '#005ea3',
        'secondary': '#5f5e5e',
        'secondary-fixed': '#e5e2e1',
        'on-tertiary': '#ffffff',
        'inverse-surface': '#3e2c26',
        'secondary-container': '#e2dfde',
        'background': '#fff8f6',
        'on-primary-fixed-variant': '#822700',
        'on-primary-container': '#fffbff',
        'on-surface-variant': '#5c4037',
        'primary': '#a63500',
        'on-error-container': '#93000a',
        'on-surface': '#281812',
        'surface-container-low': '#fff1ed',
        'surface': '#fff8f6',
        'primary-container': '#d04400',
        'tertiary-container': '#0077cd',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
